import { MemoryRecord } from '../types/MemoryTypes.js';

export const MULTI_CONTACT_RETRIEVAL_FIXTURES: MemoryRecord[] = [
  {
    id: 'ret_1',
    contactId: 'contact_alice',
    type: 'PLAN',
    title: 'Tokyo Trip Plan',
    content: 'Planning a 2-week vacation to Tokyo and Kyoto next month.',
    importance: 'HIGH',
    confidence: 0.95,
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 86400000,
    tags: ['japan', 'travel', 'tokyo'],
    source: 'extracted_heuristic',
    metadata: {},
  },
  {
    id: 'ret_2',
    contactId: 'contact_alice',
    type: 'PREFERENCE',
    title: 'Coffee Preference',
    content: 'Prefers Ethiopian dark roast coffee with oat milk.',
    importance: 'NORMAL',
    confidence: 0.92,
    createdAt: Date.now() - 172800000,
    updatedAt: Date.now() - 172800000,
    tags: ['coffee', 'preference'],
    source: 'extracted_heuristic',
    metadata: {},
  },
  {
    id: 'ret_3',
    contactId: 'contact_bob',
    type: 'GOAL',
    title: 'Computer Science Graduation',
    content: 'Graduating with a degree in Computer Science this spring.',
    importance: 'HIGH',
    confidence: 0.96,
    createdAt: Date.now() - 259200000,
    updatedAt: Date.now() - 259200000,
    tags: ['college', 'graduation', 'cs'],
    source: 'extracted_heuristic',
    metadata: {},
  },
  {
    id: 'ret_4',
    contactId: 'contact_carol',
    type: 'EVENT',
    title: 'Sister Birthday',
    content: 'Sister Sarah birthday celebration on March 15th.',
    importance: 'CRITICAL',
    confidence: 0.98,
    createdAt: Date.now() - 432000000,
    updatedAt: Date.now() - 432000000,
    tags: ['birthday', 'sister', 'event'],
    source: 'user_explicit',
    metadata: {},
  },
];
