import { AISuggestion, SuggestionCategory } from '@rapport/shared';

export class SuggestionEngine {
  /**
   * Builds system instruction specifying JSON format for multi-category suggestions
   */
  public static getStructuredOutputDirective(): string {
    return `
Return your response ONLY as a valid JSON object matching this schema:
{
  "suggestions": [
    {
      "category": "Natural Reply" | "Warm Reply" | "Creative Reply" | "Quick Reply" | "Professional Reply" | "Empathetic Reply",
      "text": "The exact suggested message text",
      "tone": "Tone name",
      "style": "Style description",
      "explanation": "Why this specific reply fits the current conversation context",
      "confidence": 0.95
    }
  ]
}

REQUIREMENTS:
1. Generate EXACTLY 3 distinct reply options matching the language of the conversation:
   - Option 1 (Safe/Natural): A smooth, standard, contextually accurate response.
   - Option 2 (Warm/Engaging): An empathetic, friendly, and warm response that encourages thread continuation.
   - Option 3 (Creative/Witty): A clever, playful, or distinctively engaging response.
2. Directly address specific details, questions, or topics from recent messages. Avoid generic fluff.
3. Do not wrap in markdown backticks. Return raw JSON.
`.trim();
  }

  /**
   * Safely parses provider raw text into validated AISuggestions
   */
  public static parseSuggestions(rawText: string, fallbackTone: string = 'Friendly'): AISuggestion[] {
    const cleaned = rawText
      .replace(/```json/gi, '')
      .replace(/```/g, '')
      .trim();

    try {
      const parsed = JSON.parse(cleaned);
      const items = Array.isArray(parsed?.suggestions) ? parsed.suggestions : Array.isArray(parsed) ? parsed : [];

      if (items.length > 0) {
        return items.map((item: any, idx: number) => ({
          id: `sug_${Date.now()}_${idx + 1}`,
          category: (item.category as SuggestionCategory) || SuggestionEngine.inferCategory(item.text, item.tone),
          text: (item.text || item.suggestedReply || '').trim(),
          tone: item.tone || fallbackTone,
          style: item.style || 'Natural',
          explanation: item.explanation || `Fits current ${item.tone || fallbackTone} conversation flow.`,
          confidence: typeof item.confidence === 'number' ? item.confidence : 0.92,
        })).filter((s: AISuggestion) => s.text.length > 0);
      }
    } catch {
      // JSON parsing failed, construct fallback suggestions from raw text
    }

    // Fallback: splitting text or single line
    const textLines = cleaned.split(/\n+/).map((l) => l.replace(/^[-*1-9.\s]+/, '').trim()).filter((l) => l.length > 2);

    if (textLines.length >= 2) {
      return textLines.slice(0, 4).map((line, idx) => ({
        id: `sug_raw_${Date.now()}_${idx + 1}`,
        category: idx === 0 ? 'Natural Reply' : idx === 1 ? 'Quick Reply' : idx === 2 ? 'Professional Reply' : 'Funny Reply',
        text: line.replace(/^"/, '').replace(/"$/, ''),
        tone: fallbackTone,
        style: 'Direct',
        explanation: 'Generated by provider matching thread context.',
        confidence: 0.9,
      }));
    }

    return [
      {
        id: `sug_single_${Date.now()}`,
        category: 'Natural Reply',
        text: cleaned.replace(/^"/, '').replace(/"$/, ''),
        tone: fallbackTone,
        style: 'Balanced',
        explanation: 'Direct AI reply matching conversation context.',
        confidence: 0.94,
      },
    ];
  }

  private static inferCategory(text: string, tone: string): SuggestionCategory {
    const lowerText = (text || '').toLowerCase();
    const lowerTone = (tone || '').toLowerCase();

    if (lowerTone.includes('flirty') || lowerTone.includes('romantic')) return 'Flirty Reply';
    if (lowerTone.includes('funny') || lowerTone.includes('humorous') || lowerTone.includes('playful')) return 'Funny Reply';
    if (lowerTone.includes('professional') || lowerTone.includes('formal')) return 'Professional Reply';
    if (lowerTone.includes('empathetic') || lowerTone.includes('supportive')) return 'Empathetic Reply';
    if (lowerText.length < 25) return 'Quick Reply';
    if (lowerText.includes('?') && lowerText.length > 30) return 'Follow-up Question';
    if (lowerText.length > 100) return 'Detailed Reply';
    return 'Natural Reply';
  }
}
