import {
  AIRequest,
  AISuggestion,
  ProviderCapabilities,
  ProviderResult,
} from '@rapport/shared';
import { AIProvider, ModelDescription } from './AIProvider.js';
import { ApiKeyManager } from './ApiKeyManager.js';
import { MetricsTracker } from './MetricsTracker.js';
import { SuggestionEngine } from '../prompts/SuggestionEngine.js';

export class GroqProvider implements AIProvider {
  public readonly id = 'groq';
  public readonly name = 'Groq Cloud Provider';

  public readonly capabilities: ProviderCapabilities = {
    supportsStreaming: true,
    supportsVision: false,
    supportsCustomSystemPrompts: true,
    maxContextTokens: 32768,
    supportedModels: [
      'llama-3.3-70b-versatile',
      'llama-3.1-8b-instant',
      'mixtral-8x7b-32768',
      'gemma2-9b-it',
    ],
  };

  private readonly keyManager = ApiKeyManager.getInstance();
  private readonly metricsTracker = MetricsTracker.getInstance();

  public async validateKey(apiKey: string): Promise<boolean> {
    try {
      const res = await fetch('https://api.groq.com/openai/v1/models', {
        method: 'GET',
        headers: { Authorization: `Bearer ${apiKey}` },
      });
      return res.status === 200;
    } catch {
      return false;
    }
  }

  public async generateReply(
    request: AIRequest,
    options?: { signal?: AbortSignal }
  ): Promise<ProviderResult> {
    const startTime = Date.now();
    const apiKey = await this.keyManager.getKey(this.id);

    if (!apiKey) {
      return {
        success: false,
        error: 'Missing Groq API Key. Please configure your API key in extension settings.',
      };
    }

    const compiledPrompt = request.compiledPrompt;
    const model = (request.options?.model as string) || 'llama-3.3-70b-versatile';
    const temperature = (request.options?.temperature as number) ?? 0.7;
    const maxTokens = (request.options?.maxTokens as number) ?? 600;

    const baseSystemPrompt = compiledPrompt?.systemPrompt || 'You are an expert conversation copilot.';
    const systemContent = `${baseSystemPrompt}\n\n${SuggestionEngine.getStructuredOutputDirective()}`;
    const userContent = compiledPrompt?.userPrompt || request.prompt || 'Suggest helpful replies for this conversation.';

    try {
      const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${apiKey}`,
        },
        signal: options?.signal,
        body: JSON.stringify({
          model,
          messages: [
            { role: 'system', content: systemContent },
            { role: 'user', content: userContent },
          ],
          temperature,
          max_tokens: maxTokens,
        }),
      });

      const latencyMs = Date.now() - startTime;

      if (!response.ok) {
        const errorText = await response.text();
        let parsedMessage = errorText;
        try {
          const json = JSON.parse(errorText);
          if (json?.error?.message) {
            parsedMessage = json.error.message;
          }
        } catch {
          // Keep raw
        }
        this.metricsTracker.record({
          providerId: this.id,
          model,
          latencyMs,
          success: false,
          timestamp: Date.now(),
          error: parsedMessage,
        });

        if (response.status === 401) return { success: false, error: `Invalid Groq API Key: ${parsedMessage}` };
        if (response.status === 429) return { success: false, error: `Groq Rate limit/Quota exceeded: ${parsedMessage}` };
        return { success: false, error: `Groq API Error (${response.status}): ${parsedMessage}` };
      }

      const data = await response.json();
      const content = data?.choices?.[0]?.message?.content || '';
      const usageTokens = data?.usage?.total_tokens;

      this.metricsTracker.record({
        providerId: this.id,
        model,
        latencyMs,
        tokens: usageTokens,
        success: true,
        timestamp: Date.now(),
      });

      const fallbackTone = request.structuredContext?.tone || 'Friendly';
      const suggestions = SuggestionEngine.parseSuggestions(content, fallbackTone);
      const primarySuggestion = suggestions[0]?.text || content.trim();

      return {
        success: true,
        data: {
          suggestedReply: primarySuggestion,
          reasoning: `Generated by Groq ${model} model.`,
          tone: suggestions[0]?.tone || fallbackTone,
          providerId: this.id,
          suggestions,
          metadata: {
            model,
            tokens: usageTokens,
            latencyMs,
          },
        },
      };
    } catch (err) {
      const latencyMs = Date.now() - startTime;
      const errorMsg = err instanceof Error ? err.message : 'Groq network error';
      this.metricsTracker.record({
        providerId: this.id,
        model,
        latencyMs,
        success: false,
        timestamp: Date.now(),
        error: errorMsg,
      });

      if (err instanceof Error && err.name === 'AbortError') {
        return { success: false, error: 'Request was cancelled by user.' };
      }

      return { success: false, error: errorMsg };
    }
  }

  public async generateReplyStream(
    request: AIRequest,
    onChunk: (chunkText: string) => void,
    options?: { signal?: AbortSignal }
  ): Promise<ProviderResult> {
    const startTime = Date.now();
    const apiKey = await this.keyManager.getKey(this.id);

    if (!apiKey) {
      return {
        success: false,
        error: 'Missing Groq API Key. Please configure your API key in extension settings.',
      };
    }

    const compiledPrompt = request.compiledPrompt;
    const model = (request.options?.model as string) || 'llama-3.3-70b-versatile';
    const temperature = (request.options?.temperature as number) ?? 0.7;
    const maxTokens = (request.options?.maxTokens as number) ?? 600;

    const baseSystemPrompt = compiledPrompt?.systemPrompt || 'You are an expert conversation copilot.';
    const systemContent = `${baseSystemPrompt}\n\n${SuggestionEngine.getStructuredOutputDirective()}`;
    const userContent = compiledPrompt?.userPrompt || request.prompt || 'Suggest helpful replies for this conversation.';

    try {
      const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${apiKey}`,
        },
        signal: options?.signal,
        body: JSON.stringify({
          model,
          messages: [
            { role: 'system', content: systemContent },
            { role: 'user', content: userContent },
          ],
          temperature,
          max_tokens: maxTokens,
          stream: true,
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        let parsedMessage = errorText;
        try {
          const json = JSON.parse(errorText);
          if (json?.error?.message) {
            parsedMessage = json.error.message;
          }
        } catch {
          // Keep raw
        }
        if (response.status === 401) return { success: false, error: `Invalid Groq API Key: ${parsedMessage}` };
        if (response.status === 429) return { success: false, error: `Groq Rate limit/Quota exceeded: ${parsedMessage}` };
        return { success: false, error: `Groq Streaming API Error (${response.status}): ${parsedMessage}` };
      }

      const reader = response.body?.getReader();
      if (!reader) {
        return { success: false, error: 'Groq response body reader unavailable.' };
      }

      const decoder = new TextDecoder('utf-8');
      let fullContent = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const chunk = decoder.decode(value, { stream: true });
        const lines = chunk.split('\n');

        for (const line of lines) {
          const trimmed = line.trim();
          if (trimmed.startsWith('data: ')) {
            const dataStr = trimmed.slice(6);
            if (dataStr === '[DONE]') continue;
            try {
              const json = JSON.parse(dataStr);
              const delta = json?.choices?.[0]?.delta?.content || '';
              if (delta) {
                fullContent += delta;
                onChunk(delta);
              }
            } catch {
              // Ignore non-json stream lines
            }
          }
        }
      }

      const latencyMs = Date.now() - startTime;
      const fallbackTone = request.structuredContext?.tone || 'Friendly';
      const suggestions = SuggestionEngine.parseSuggestions(fullContent, fallbackTone);

      return {
        success: true,
        data: {
          suggestedReply: suggestions[0]?.text || fullContent.trim(),
          reasoning: `Streamed by Groq ${model} model.`,
          tone: suggestions[0]?.tone || fallbackTone,
          providerId: this.id,
          suggestions,
          metadata: { model, latencyMs },
        },
      };
    } catch (err) {
      if (err instanceof Error && err.name === 'AbortError') {
        return { success: false, error: 'Request was cancelled by user.' };
      }
      return { success: false, error: err instanceof Error ? err.message : 'Groq stream error' };
    }
  }

  public async verifyKey(apiKey: string): Promise<boolean> {
    return this.validateKey(apiKey);
  }

  public async listModels(): Promise<ModelDescription[]> {
    const cached = await this.getCachedModels();
    if (cached && cached.length > 0) {
      return cached;
    }
    return APPROVED_GROQ_MODELS;
  }

  public async refreshModels(): Promise<ModelDescription[]> {
    const apiKey = await this.keyManager.getKey(this.id);
    if (!apiKey) {
      return APPROVED_GROQ_MODELS;
    }

    try {
      const res = await fetch('https://api.groq.com/openai/v1/models', {
        method: 'GET',
        headers: { Authorization: `Bearer ${apiKey}` },
      });
      if (res.status !== 200) {
        return APPROVED_GROQ_MODELS;
      }
      const data = await res.json();
      const rawModels = data.data || [];

      // Filter out: Preview models, Deprecated models, Experimental models, Retired models
      const filtered = rawModels.filter((m: any) => {
        const idLower = (m.id || '').toLowerCase();
        
        // Filter out: preview, deprecated, retired, whisper, vision, embedding, guard, experimental
        if (idLower.includes('preview') ||
            idLower.includes('deprecated') ||
            idLower.includes('retired') ||
            idLower.includes('whisper') ||
            idLower.includes('vision') ||
            idLower.includes('embed') ||
            idLower.includes('guard') ||
            idLower.includes('lc-') ||
            idLower.includes('internal')) {
          return false;
        }

        // Keep: llama, mixtral, gemma
        if (idLower.includes('llama') || idLower.includes('mixtral') || idLower.includes('gemma')) {
          return true;
        }
        return false;
      });

      // Map models to Clean Display Names and metadata
      const mapped: ModelDescription[] = filtered.map((m: any) => {
        const rawId = m.id;
        const existing = APPROVED_GROQ_MODELS.find(x => x.id === rawId);
        if (existing) return existing;

        const idLower = rawId.toLowerCase();
        let displayName = rawId;
        // Clean display name, e.g. llama-3.3-70b-versatile -> LLaMA 3.3 70B
        displayName = rawId
          .split('-')
          .map((word: string) => {
            if (word === 'llama') return 'LLaMA';
            if (word === 'it') return 'IT';
            return word.charAt(0).toUpperCase() + word.slice(1);
          })
          .join(' ')
          .replace(' Versatile', '')
          .replace(' Instant', '');

        let speed = 'Fast';
        let reasoning = 'Standard';
        let useCase = 'Fast responses for daily messaging.';
        let isRecommended = false;

        if (idLower.includes('8b') || idLower.includes('instant') || idLower.includes('8b-instant')) {
          speed = 'Blazing';
          reasoning = 'Standard';
          useCase = 'Fastest and lowest cost.';
        } else if (idLower.includes('70b') || idLower.includes('versatile')) {
          speed = 'Fast';
          reasoning = 'High';
          useCase = 'Best reasoning for emotionally complex conversations.';
          isRecommended = true;
        } else if (idLower.includes('mixtral') || idLower.includes('8x7b')) {
          speed = 'Moderate';
          reasoning = 'Standard';
          useCase = 'High-quality mixture of experts model for long contexts.';
        } else if (idLower.includes('gemma')) {
          speed = 'Fast';
          reasoning = 'Standard';
          useCase = 'Google Gemma instruction tuned model optimized for conversational logic.';
        }

        return {
          id: rawId,
          displayName,
          speed,
          reasoning,
          useCase,
          contextLength: idLower.includes('70b') || idLower.includes('mixtral') ? '32K tokens' : '8K tokens',
          isRecommended,
        };
      });

      // Sort: Recommended on top, then default, then others
      const sorted = mapped.sort((a, b) => {
        const aVal = (a.isRecommended ? 2 : 0) + (a.isDefault ? 1 : 0);
        const bVal = (b.isRecommended ? 2 : 0) + (b.isDefault ? 1 : 0);
        return bVal - aVal;
      });

      await this.setCachedModels(sorted);
      return sorted.length > 0 ? sorted : APPROVED_GROQ_MODELS;
    } catch (err) {
      console.warn('[GroqProvider] Failed to refresh models:', err);
      return APPROVED_GROQ_MODELS;
    }
  }

  public async selectModel(modelId: string): Promise<void> {
    console.log(`[GroqProvider] Selected model: ${modelId}`);
  }

  public async generate(request: AIRequest, options?: { signal?: AbortSignal }): Promise<ProviderResult> {
    return this.generateReply(request, options);
  }

  private async getCachedModels(): Promise<ModelDescription[] | null> {
    try {
      const chromeObj = typeof window !== 'undefined' ? (window as any).chrome : null;
      if (chromeObj && chromeObj.storage && chromeObj.storage.local) {
        const key = `rapport_models_cache_${this.id}`;
        const res = await chromeObj.storage.local.get([key]);
        return res[key] || null;
      }
    } catch {}
    return null;
  }

  private async setCachedModels(models: ModelDescription[]): Promise<void> {
    try {
      const chromeObj = typeof window !== 'undefined' ? (window as any).chrome : null;
      if (chromeObj && chromeObj.storage && chromeObj.storage.local) {
        const key = `rapport_models_cache_${this.id}`;
        await chromeObj.storage.local.set({ [key]: models });
      }
    } catch {}
  }
}

const APPROVED_GROQ_MODELS: ModelDescription[] = [
  {
    id: 'llama-3.3-70b-versatile',
    displayName: 'LLaMA 3.3 70B',
    speed: 'Fast',
    reasoning: 'High',
    useCase: 'Best reasoning for emotionally complex conversations.',
    contextLength: '32K tokens',
    isRecommended: true,
    isDefault: true,
  },
  {
    id: 'llama-3.1-8b-instant',
    displayName: 'LLaMA 3.1 8B',
    speed: 'Blazing',
    reasoning: 'Standard',
    useCase: 'Fastest and lowest cost.',
    contextLength: '8K tokens',
  },
  {
    id: 'mixtral-8x7b-32768',
    displayName: 'Mixtral 8x7B',
    speed: 'Moderate',
    reasoning: 'Standard',
    useCase: 'High-quality mixture of experts model for long contexts.',
    contextLength: '32K tokens',
  },
  {
    id: 'gemma2-9b-it',
    displayName: 'Gemma 2 9B',
    speed: 'Fast',
    reasoning: 'Standard',
    useCase: 'Google Gemma instruction tuned model optimized for conversational logic.',
    contextLength: '8K tokens',
  }
];
